services:
  chat-ai-app:
    build:
      context: .
      args:
        NEXT_PUBLIC_APP_ID: ${NEXT_PUBLIC_APP_ID:-59a6b61c-3834-4f72-81f7-b7a816833ec0}
        NEXT_PUBLIC_APP_KEY: ${NEXT_PUBLIC_APP_KEY:-app-ac5u0SXBSfycKSb9W2jaFbFI}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-https://dify.yswg360.com/v1}
        NEXT_PUBLIC_API_ORG_URL: ${NEXT_PUBLIC_API_ORG_URL:-https://qw.yswg360.com}
        NEXT_PUBLIC_BASE_PATH: ${NEXT_PUBLIC_BASE_PATH:-/chat}
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3020}:3020"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
