version: '3'
services:
  web:
    build: .
    container_name: ai-hub
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_DOCMEE_API_KEY=ak_rJDEMCpsEp6TEXI4b0
